### ISSUE TITLE
Feature request: recurring payments

### ISSUE THREAD

**Issue by IlyaasK** [xorum-io/open_money_tracker#35] opened 2023-11-27 03:59 UTC
Like rent and gym. Option for yearly, weekly, monthly, 6 monthly and daily recurring expenses.

**Comment by yev-kanivets** [comment] 2023-11-27 07:12
Duplicate of https://github.com/xorum-io/open_money_tracker/issues/16

**Closed by yev-kanivets** 2023-11-27 07:12 UTC
